-- ============================================================
-- Content seed data
-- GENERATED FILE — do not hand-edit. Regenerate with:
--   node database/scripts/generate-seed.mjs
-- Source of truth is the frontend data files, not this file.
-- ============================================================

-- product_categories
insert into product_categories (slug, label, icon, sort_order) values ('industrial-acrylic-components', 'Industrial Acrylic Components', 'Layers', 0);
insert into product_categories (slug, label, icon, sort_order) values ('polycarbonate-components', 'Polycarbonate Components', 'Boxes', 1);
insert into product_categories (slug, label, icon, sort_order) values ('machine-guards', 'Machine Guards', 'ShieldCheck', 2);
insert into product_categories (slug, label, icon, sort_order) values ('protective-covers', 'Protective Covers', 'Shield', 3);
insert into product_categories (slug, label, icon, sort_order) values ('acrylic-tanks', 'Acrylic Tanks', 'Droplet', 4);
insert into product_categories (slug, label, icon, sort_order) values ('acrylic-boxes', 'Acrylic Boxes', 'Package', 5);
insert into product_categories (slug, label, icon, sort_order) values ('acrylic-cabinets', 'Acrylic Cabinets', 'Archive', 6);
insert into product_categories (slug, label, icon, sort_order) values ('inspection-windows', 'Inspection Windows', 'Eye', 7);
insert into product_categories (slug, label, icon, sort_order) values ('sight-glasses', 'Sight Glasses', 'Aperture', 8);
insert into product_categories (slug, label, icon, sort_order) values ('transparent-enclosures', 'Transparent Enclosures', 'Box', 9);
insert into product_categories (slug, label, icon, sort_order) values ('custom-fabricated-components', 'Custom Fabricated Components', 'Wrench', 10);
insert into product_categories (slug, label, icon, sort_order) values ('display-commercial-products', 'Display & Commercial Products', 'Store', 11);

-- capabilities
insert into capabilities (slug, label, icon, animation_type, description, applications, materials, use_cases, sort_order) values ('cnc-routing', 'CNC Routing', 'Cog', 'route', 'Computer-controlled routing for precise profiles, cutouts and edge detailing on flat sheet stock, guided directly by your drawing or CAD file.', ARRAY['Machine panels', 'Enclosure cutouts', 'Signage components', 'Display fixtures'], ARRAY['Acrylic', 'Polycarbonate'], ARRAY['Panels with multiple cutouts and mounting holes', 'Parts requiring consistent repeat geometry across a production run', 'Components with curved or irregular edge profiles'], 0);
insert into capabilities (slug, label, icon, animation_type, description, applications, materials, use_cases, sort_order) values ('laser-cutting', 'Laser Cutting', 'Zap', 'laser', 'Laser-guided cutting for clean edges and fine detail work, suited to intricate profiles that are difficult to achieve with mechanical cutting alone.', ARRAY['Detailed enclosure parts', 'Decorative and branded elements', 'Small precision components', 'Prototype parts'], ARRAY['Acrylic', 'Polycarbonate'], ARRAY['Intricate or detailed profile cuts', 'Small-batch prototyping ahead of a production run', 'Parts with fine internal features'], 1);
insert into capabilities (slug, label, icon, animation_type, description, applications, materials, use_cases, sort_order) values ('acrylic-cutting', 'Acrylic Cutting', 'Scissors', 'cut', 'Straight and profile cutting of acrylic sheet to size, from single pieces to production quantities.', ARRAY['Machine guards', 'Display panels', 'Protective screens', 'Enclosure panels'], ARRAY['Acrylic'], ARRAY['Sheet cut to size for a defined panel dimension', 'Multiple identical panels for a production run', 'Panels that will be bonded or assembled into a larger structure'], 2);
insert into capabilities (slug, label, icon, animation_type, description, applications, materials, use_cases, sort_order) values ('polycarbonate-cutting', 'Polycarbonate Cutting', 'Shield', 'cut', 'Cutting of polycarbonate sheet for components where impact resistance matters alongside dimensional accuracy.', ARRAY['Machine guards', 'Protective covers', 'Industrial glazing', 'Safety screens'], ARRAY['Polycarbonate'], ARRAY['Guards and covers for moving machine parts', 'Impact-resistant panels for industrial environments', 'Components requiring both clarity and durability'], 3);
insert into capabilities (slug, label, icon, animation_type, description, applications, materials, use_cases, sort_order) values ('acrylic-bending', 'Acrylic Bending', 'GitMerge', 'bend', 'Heat-formed bending of acrylic sheet to specified angles, producing folded or curved components without seams.', ARRAY['Display stands', 'Enclosure corners', 'Formed panels', 'Point-of-sale fixtures'], ARRAY['Acrylic'], ARRAY['Single-piece components that would otherwise need bonded corners', 'Formed panels with a consistent bend angle across a batch', 'Parts combining flat sections with a folded edge'], 4);
insert into capabilities (slug, label, icon, animation_type, description, applications, materials, use_cases, sort_order) values ('polycarbonate-bending', 'Polycarbonate Bending', 'GitBranch', 'bend', 'Controlled bending of polycarbonate sheet, taking advantage of its flexibility for formed components that need to withstand impact.', ARRAY['Curved guards', 'Formed covers', 'Protective housings', 'Structural panel corners'], ARRAY['Polycarbonate'], ARRAY['Curved guards that follow a machine''s contour', 'Formed covers requiring a folded edge for rigidity', 'Components where a bonded seam would be a weak point'], 5);
insert into capabilities (slug, label, icon, animation_type, description, applications, materials, use_cases, sort_order) values ('bonding', 'Bonding', 'Layers', 'bond', 'Solvent and adhesive bonding to join acrylic and polycarbonate components into finished multi-part assemblies.', ARRAY['Enclosures', 'Display cases', 'Multi-panel guards', 'Assembled fixtures'], ARRAY['Acrylic', 'Polycarbonate'], ARRAY['Multi-panel enclosures assembled from separate cut pieces', 'Components too large or complex to form from a single sheet', 'Assemblies combining acrylic and polycarbonate parts'], 6);
insert into capabilities (slug, label, icon, animation_type, description, applications, materials, use_cases, sort_order) values ('custom-fabrication', 'Custom Fabrication', 'Wrench', 'assemble', 'End-to-end fabrication from your drawing, dimensions, sample or specification — combining cutting, forming, bonding and finishing into one completed component.', ARRAY['Non-standard machine components', 'One-off engineering parts', 'Bespoke enclosures', 'Project-specific fixtures'], ARRAY['Acrylic', 'Polycarbonate'], ARRAY['Parts that don''t match any standard catalogue item', 'Components built directly from a customer-supplied drawing or sample', 'Projects needing multiple processes combined into one finished part'], 7);

-- industries
insert into industries (slug, label, icon, description, common_requirements, applications, sort_order) values ('pharmaceutical', 'Pharmaceutical', 'Pill', 'Cleanable, chemical-resistant components for pharmaceutical production and quality environments.', ARRAY['Low-particulate, easy-to-clean surfaces', 'Chemical resistance to common cleaning agents', 'Visibility into enclosed processes'], ARRAY['Cleanroom viewing panels', 'Process enclosure windows', 'Equipment guarding'], 0);
insert into industries (slug, label, icon, description, common_requirements, applications, sort_order) values ('engineering', 'Engineering', 'Compass', 'Fabricated components that fit directly into engineering assemblies and equipment builds.', ARRAY['Dimensional accuracy to a supplied drawing', 'Repeatable geometry across a production run', 'Components that integrate with metal and mechanical parts'], ARRAY['Machine panelling', 'Equipment enclosures', 'Structural infill components'], 1);
insert into industries (slug, label, icon, description, common_requirements, applications, sort_order) values ('manufacturing', 'Manufacturing', 'Factory', 'Guarding, panelling and enclosures fabricated for production-floor equipment.', ARRAY['Durable components for continuous production use', 'Guards that protect personnel without blocking visibility', 'Consistent quality across repeat orders'], ARRAY['Production line guarding', 'Equipment covers', 'Conveyor safety panels'], 2);
insert into industries (slug, label, icon, description, common_requirements, applications, sort_order) values ('chemical', 'Chemical', 'FlaskConical', 'Chemically-aware component selection for process and containment environments.', ARRAY['Material selection suited to chemical exposure', 'Sealed, bonded assemblies', 'Clear visibility for process monitoring'], ARRAY['Containment tanks', 'Process sight glasses', 'Enclosed monitoring windows'], 3);
insert into industries (slug, label, icon, description, common_requirements, applications, sort_order) values ('food-processing', 'Food Processing', 'Utensils', 'Hygienic, cleanable components for food production and packaging lines.', ARRAY['Smooth, cleanable surfaces', 'Components suited to washdown environments', 'Guarding that maintains line visibility'], ARRAY['Line guarding', 'Equipment covers', 'Inspection panels'], 4);
insert into industries (slug, label, icon, description, common_requirements, applications, sort_order) values ('packaging', 'Packaging', 'Package', 'Guards, covers and fixtures fabricated for packaging line equipment.', ARRAY['Fast-cycle equipment guarding', 'Clear panels for line-of-sight monitoring', 'Components that withstand repeated handling'], ARRAY['Packaging line guarding', 'Equipment covers', 'Point-of-sale display fixtures'], 5);
insert into industries (slug, label, icon, description, common_requirements, applications, sort_order) values ('automotive', 'Automotive', 'Car', 'Formed and fabricated components for automotive production and testing environments.', ARRAY['Impact-resistant materials for production floors', 'Formed components matching equipment contours', 'Consistent repeat-order quality'], ARRAY['Test rig guarding', 'Equipment covers', 'Formed protective panels'], 6);
insert into industries (slug, label, icon, description, common_requirements, applications, sort_order) values ('industrial-machinery', 'Industrial Machinery', 'Cog', 'Guards, panels and enclosures fabricated to fit specific machine geometries.', ARRAY['Guards fitted to exact machine geometry', 'Durable materials for continuous operation', 'Fast turnaround for repeat orders'], ARRAY['Machine guarding', 'Control panel fascias', 'Equipment enclosures'], 7);
insert into industries (slug, label, icon, description, common_requirements, applications, sort_order) values ('laboratory', 'Laboratory', 'TestTube', 'Precision-fabricated components for laboratory equipment and workspace fixtures.', ARRAY['Optical clarity for observation', 'Chemical resistance for lab environments', 'Precise, repeatable dimensions'], ARRAY['Equipment viewing windows', 'Sample enclosures', 'Storage and organisation fixtures'], 8);
insert into industries (slug, label, icon, description, common_requirements, applications, sort_order) values ('retail', 'Retail', 'ShoppingBag', 'Display and fixture fabrication for retail and commercial environments.', ARRAY['Visual presentation quality', 'Durable fixtures for frequent handling', 'Custom sizing per store or display layout'], ARRAY['Retail display fixtures', 'Point-of-sale stands', 'Showroom cabinetry'], 9);

-- industry_categories
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'pharmaceutical'), (select id from product_categories where slug = 'transparent-enclosures'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'pharmaceutical'), (select id from product_categories where slug = 'inspection-windows'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'pharmaceutical'), (select id from product_categories where slug = 'sight-glasses'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'pharmaceutical'), (select id from product_categories where slug = 'machine-guards'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'engineering'), (select id from product_categories where slug = 'industrial-acrylic-components'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'engineering'), (select id from product_categories where slug = 'custom-fabricated-components'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'engineering'), (select id from product_categories where slug = 'machine-guards'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'manufacturing'), (select id from product_categories where slug = 'machine-guards'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'manufacturing'), (select id from product_categories where slug = 'protective-covers'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'manufacturing'), (select id from product_categories where slug = 'polycarbonate-components'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'chemical'), (select id from product_categories where slug = 'acrylic-tanks'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'chemical'), (select id from product_categories where slug = 'sight-glasses'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'chemical'), (select id from product_categories where slug = 'transparent-enclosures'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'food-processing'), (select id from product_categories where slug = 'machine-guards'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'food-processing'), (select id from product_categories where slug = 'protective-covers'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'food-processing'), (select id from product_categories where slug = 'industrial-acrylic-components'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'packaging'), (select id from product_categories where slug = 'machine-guards'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'packaging'), (select id from product_categories where slug = 'protective-covers'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'packaging'), (select id from product_categories where slug = 'display-commercial-products'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'automotive'), (select id from product_categories where slug = 'polycarbonate-components'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'automotive'), (select id from product_categories where slug = 'machine-guards'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'automotive'), (select id from product_categories where slug = 'custom-fabricated-components'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'industrial-machinery'), (select id from product_categories where slug = 'machine-guards'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'industrial-machinery'), (select id from product_categories where slug = 'industrial-acrylic-components'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'industrial-machinery'), (select id from product_categories where slug = 'polycarbonate-components'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'laboratory'), (select id from product_categories where slug = 'sight-glasses'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'laboratory'), (select id from product_categories where slug = 'inspection-windows'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'laboratory'), (select id from product_categories where slug = 'acrylic-boxes'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'retail'), (select id from product_categories where slug = 'display-commercial-products'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'retail'), (select id from product_categories where slug = 'acrylic-cabinets'));
insert into industry_categories (industry_id, category_id) values ((select id from industries where slug = 'retail'), (select id from product_categories where slug = 'acrylic-boxes'));

-- industry_capabilities
-- industry_capabilities
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'pharmaceutical'), (select id from capabilities where slug = 'custom-fabrication'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'pharmaceutical'), (select id from capabilities where slug = 'bonding'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'pharmaceutical'), (select id from capabilities where slug = 'cnc-routing'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'engineering'), (select id from capabilities where slug = 'cnc-routing'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'engineering'), (select id from capabilities where slug = 'laser-cutting'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'engineering'), (select id from capabilities where slug = 'custom-fabrication'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'manufacturing'), (select id from capabilities where slug = 'acrylic-cutting'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'manufacturing'), (select id from capabilities where slug = 'acrylic-bending'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'manufacturing'), (select id from capabilities where slug = 'bonding'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'chemical'), (select id from capabilities where slug = 'bonding'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'chemical'), (select id from capabilities where slug = 'custom-fabrication'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'chemical'), (select id from capabilities where slug = 'acrylic-cutting'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'food-processing'), (select id from capabilities where slug = 'acrylic-cutting'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'food-processing'), (select id from capabilities where slug = 'cnc-routing'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'food-processing'), (select id from capabilities where slug = 'bonding'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'packaging'), (select id from capabilities where slug = 'acrylic-cutting'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'packaging'), (select id from capabilities where slug = 'laser-cutting'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'packaging'), (select id from capabilities where slug = 'custom-fabrication'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'automotive'), (select id from capabilities where slug = 'acrylic-bending'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'automotive'), (select id from capabilities where slug = 'cnc-routing'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'automotive'), (select id from capabilities where slug = 'custom-fabrication'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'industrial-machinery'), (select id from capabilities where slug = 'cnc-routing'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'industrial-machinery'), (select id from capabilities where slug = 'acrylic-bending'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'industrial-machinery'), (select id from capabilities where slug = 'bonding'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'laboratory'), (select id from capabilities where slug = 'laser-cutting'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'laboratory'), (select id from capabilities where slug = 'cnc-routing'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'laboratory'), (select id from capabilities where slug = 'custom-fabrication'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'retail'), (select id from capabilities where slug = 'acrylic-cutting'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'retail'), (select id from capabilities where slug = 'acrylic-bending'));
insert into industry_capabilities (industry_id, capability_id) values ((select id from industries where slug = 'retail'), (select id from capabilities where slug = 'custom-fabrication'));
-- products
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('acrylic-machine-panel', 'Acrylic Machine Panel', (select id from product_categories where slug = 'industrial-acrylic-components'), 'Fabricated acrylic panelling for machine housings and control panel fascias.', ARRAY['Machine housings', 'Control panel fascias', 'Equipment panelling'], ARRAY['Acrylic'], true);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('acrylic-structural-component', 'Acrylic Structural Component', (select id from product_categories where slug = 'industrial-acrylic-components'), 'Custom acrylic components fabricated to fit within larger equipment assemblies.', ARRAY['Equipment assemblies', 'Structural infill panels'], ARRAY['Acrylic'], false);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('polycarbonate-impact-panel', 'Polycarbonate Impact Panel', (select id from product_categories where slug = 'polycarbonate-components'), 'Impact-resistant polycarbonate panels for demanding industrial settings.', ARRAY['Industrial enclosures', 'Impact zones', 'Safety barriers'], ARRAY['Polycarbonate'], false);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('polycarbonate-structural-part', 'Polycarbonate Structural Part', (select id from product_categories where slug = 'polycarbonate-components'), 'Formed polycarbonate components for structural and protective applications.', ARRAY['Protective structures', 'Equipment framing'], ARRAY['Polycarbonate'], false);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('cnc-machine-guard', 'CNC Machine Guard', (select id from product_categories where slug = 'machine-guards'), 'Transparent guarding fabricated to fit around CNC and automated machinery.', ARRAY['CNC machines', 'Automated production lines'], ARRAY['Acrylic', 'Polycarbonate'], true);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('conveyor-guard-panel', 'Conveyor Guard Panel', (select id from product_categories where slug = 'machine-guards'), 'Guard panelling for conveyor systems, allowing visibility while protecting personnel.', ARRAY['Conveyor systems', 'Production floors'], ARRAY['Acrylic', 'Polycarbonate'], false);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('equipment-protective-cover', 'Equipment Protective Cover', (select id from product_categories where slug = 'protective-covers'), 'Fitted covers protecting equipment from dust, debris and incidental contact.', ARRAY['Idle equipment protection', 'Dust protection'], ARRAY['Acrylic', 'Polycarbonate'], false);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('control-panel-cover', 'Control Panel Cover', (select id from product_categories where slug = 'protective-covers'), 'Clear covers for control panels and switchgear, maintaining visibility while protecting components.', ARRAY['Control panels', 'Switchgear enclosures'], ARRAY['Acrylic'], false);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('custom-acrylic-tank', 'Custom Acrylic Tank', (select id from product_categories where slug = 'acrylic-tanks'), 'Fabricated acrylic tanks built to your capacity and configuration requirements.', ARRAY['Process fluid containment', 'Display tanks', 'Laboratory use'], ARRAY['Acrylic'], true);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('acrylic-storage-box', 'Acrylic Storage Box', (select id from product_categories where slug = 'acrylic-boxes'), 'Clear acrylic boxes fabricated for storage, display or organisation.', ARRAY['Component storage', 'Retail display', 'Organisation systems'], ARRAY['Acrylic'], false);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('acrylic-display-cabinet', 'Acrylic Display Cabinet', (select id from product_categories where slug = 'acrylic-cabinets'), 'Cabinets fabricated from acrylic panels for display or light storage use.', ARRAY['Retail display', 'Showroom fixtures'], ARRAY['Acrylic'], false);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('machine-inspection-window', 'Machine Inspection Window', (select id from product_categories where slug = 'inspection-windows'), 'Fitted viewing windows for machine housings, allowing inspection without opening the enclosure.', ARRAY['Machine housings', 'Process monitoring'], ARRAY['Acrylic', 'Polycarbonate'], false);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('process-sight-glass', 'Process Sight Glass', (select id from product_categories where slug = 'sight-glasses'), 'Fabricated sight glass components for visual monitoring of enclosed processes.', ARRAY['Tank level viewing', 'Process monitoring'], ARRAY['Acrylic'], false);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('transparent-equipment-enclosure', 'Transparent Equipment Enclosure', (select id from product_categories where slug = 'transparent-enclosures'), 'Fully enclosed transparent housings for equipment requiring visibility and protection.', ARRAY['Sensitive equipment housing', 'Cleanroom-adjacent use'], ARRAY['Acrylic', 'Polycarbonate'], true);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('custom-fabricated-part', 'Custom Fabricated Part', (select id from product_categories where slug = 'custom-fabricated-components'), 'Built directly from your drawing, sample or specification when nothing standard fits.', ARRAY['Non-standard requirements', 'One-off engineering parts'], ARRAY['Acrylic', 'Polycarbonate'], true);
insert into products (slug, name, category_id, short_description, applications, materials, featured) values ('commercial-display-fixture', 'Commercial Display Fixture', (select id from product_categories where slug = 'display-commercial-products'), 'Acrylic display and point-of-sale fixtures fabricated for retail and commercial spaces.', ARRAY['Retail displays', 'Point-of-sale fixtures', 'Showrooms'], ARRAY['Acrylic'], false);

-- blog_posts
insert into blog_posts (slug, title, excerpt, content, author, published, published_at) values ('acrylic-vs-polycarbonate', 'Acrylic vs Polycarbonate: Which Material Fits Your Application?', 'Both are common choices for transparent fabricated components, but they suit different jobs. Here''s how to think about the choice.', 'Acrylic and polycarbonate are the two materials we fabricate with, and they''re often considered for the same kind of component — a guard, a window, an enclosure — which makes the choice between them a genuinely common question.

The short version: acrylic offers better optical clarity and is generally easier to cut, machine, and polish to a finished edge. Polycarbonate is significantly more impact-resistant and holds up better under sharp impact, which matters most for machine guards and safety-critical enclosures.

Neither material is a strict upgrade over the other — the right choice depends on what the part actually needs to do. A display panel or light-diffusion enclosure, where clarity and finish matter most and impact risk is low, usually favours acrylic. A guard around moving machinery, where an impact needs to be survivable rather than just unlikely, usually favours polycarbonate.

Cost, weight, and surface durability are worth weighing too: acrylic tends to be more affordable and scratch-resistant on the surface, while polycarbonate is the more forgiving choice if the part will see rough handling or occasional contact.

If you''re not sure which fits your application, our Material Selector covers both in more depth, or you can send your requirement directly and we''ll advise based on what the part needs to do.', 'Henil Enterprise', true, '2026-01-08');
insert into blog_posts (slug, title, excerpt, content, author, published, published_at) values ('choosing-acrylic-thickness', 'Choosing Acrylic Thickness: What Actually Matters', 'There''s no single right thickness — it depends on span, load, and how the part is mounted. Here''s what to think through before you specify one.', 'We get asked about acrylic thickness more than almost anything else, and the honest answer is that there isn''t a default — the right thickness depends on the part, not a rule of thumb.

A few factors do most of the work in that decision. Unsupported span matters a lot: a panel that''s fully framed on all four edges can run thinner than one that''s only supported on two sides or cantilevered out from a bracket. Expected load matters too — a static display panel and a guard that might get leaned on are different problems even if they''re the same size.

Visibility and optical requirements play a role as well. Thicker sheet can introduce a slight tint or distortion at the edges depending on the application, which matters more for some uses than others. And mounting method interacts with all of the above — a bonded, fully-supported enclosure has different requirements than a panel held by a handful of fasteners.

Because thickness is genuinely application-specific, we don''t quote a fixed range up front — we work through it with you based on the actual part, its span, its load, and how it''ll be mounted. If you already know your application, sending that context with your quote request lets us recommend a thickness rather than you having to guess one.', 'Henil Enterprise', true, '2026-01-15');
insert into blog_posts (slug, title, excerpt, content, author, published, published_at) values ('industrial-machine-guards', 'What Makes a Good Industrial Machine Guard', 'A machine guard has one job that matters more than any other: staying between a person and a hazard. Here''s what that means for material and fabrication choices.', 'A machine guard exists to do one thing: keep a person separated from a hazard while the process behind it keeps running. Everything about how it''s specified and built follows from that.

Visibility is usually non-negotiable — an operator needs to see the process to run it safely, which is exactly why guards get fabricated from acrylic or polycarbonate rather than solid metal panelling in the first place. The material choice between the two often comes down to the kind of hazard involved: for guards around fast-moving or high-force machinery, polycarbonate''s impact resistance is usually the deciding factor.

Fit matters as much as material. A guard that''s been fabricated to the exact geometry of the machine it protects — using CNC routing for mounting points and cutouts, and bending or bonding where the guard needs to wrap around a corner rather than sit flat — stays in place and stays effective. A guard that was adapted from a generic size rarely fits as well, and fit is exactly where a guard earns its purpose.

This is also why machine guards are almost always a custom-fabrication conversation rather than a catalogue purchase — every machine''s geometry, mounting points, and hazard zones are a little different, even within the same equipment class.

If you''re specifying a guard for a specific machine, sending its mounting points and the geometry you need to clear (a drawing, a sketch, or even photos) gets us to an accurate quote faster than a general description.', 'Henil Enterprise', true, '2026-01-22');
insert into blog_posts (slug, title, excerpt, content, author, published, published_at) values ('acrylic-fabrication', 'What Acrylic Fabrication Actually Involves', 'From flat sheet to a finished component — an overview of the processes that turn acrylic stock into a usable part.', '"Acrylic fabrication" covers a handful of distinct processes, and most real components need more than one of them combined.

Cutting comes first — CNC routing for profiles, cutouts, and mounting holes, or laser cutting where the geometry is finer or more intricate than routing handles well. Both start from flat sheet stock and produce the part''s outline.

From there, forming and joining processes turn flat pieces into a finished shape. Bending heat-forms acrylic to a specified angle for folded or curved components, useful anywhere a single-piece part is preferable to a bonded corner. Bonding joins separate pieces — solvent or adhesive bonding — into a multi-part assembly, which is how larger or more complex components get built from pieces too big or too shaped to form from one sheet.

The order these happen in, and which ones a given part actually needs, depends entirely on the component. A simple flat panel might only need cutting. A multi-panel enclosure needs cutting, bonding, and often bending to get the corners right.

What ties all of it together is that we fabricate to your drawing rather than adapting a standard part — the process sequence gets built around what you actually need, not the other way around.', 'Henil Enterprise', true, '2026-01-29');
insert into blog_posts (slug, title, excerpt, content, author, published, published_at) values ('polycarbonate-fabrication', 'Polycarbonate Fabrication: What''s Different From Acrylic', 'The same core processes apply, but polycarbonate''s properties change a few things about how it''s handled and where it''s used.', 'Polycarbonate goes through largely the same fabrication processes as acrylic — cutting, CNC routing, bending, bonding — but its properties change how each of those gets approached and what it''s typically used for.

The material''s impact resistance is the headline property, and it''s why polycarbonate fabrication skews toward guards, covers, and enclosures where surviving an impact matters more than optical perfection. That same toughness, though, means it behaves a little differently under cutting and forming than acrylic does, which is part of why we treat acrylic and polycarbonate cutting as distinct capabilities rather than one generic "cutting" process.

Polycarbonate is also more UV-sensitive than acrylic in its base form, which is worth factoring in for anything headed outdoors or exposed to prolonged direct light — a UV-stable grade or coating is a reasonable thing to specify for that kind of application.

Bonding polycarbonate follows the same general logic as acrylic — joining separate pieces into a finished assembly — and it''s often the right approach for polycarbonate enclosures and multi-panel guards where the component is too large or too shaped to form from a single sheet.

If your application is outdoor, high-impact, or otherwise demanding, it''s worth mentioning that context when you request a quote — it affects both material choice and finish.', 'Henil Enterprise', true, '2026-02-05');
insert into blog_posts (slug, title, excerpt, content, author, published, published_at) values ('cnc-acrylic-cutting', 'CNC Acrylic Cutting: When Routing Is the Right Call', 'CNC routing and laser cutting can both produce a cut acrylic part — here''s how to think about which one fits your geometry.', 'CNC routing is computer-controlled cutting guided directly by a drawing or CAD file, and it''s one of the two main ways we cut acrylic — the other being laser cutting.

Routing tends to be the better fit for panels with multiple cutouts and mounting holes, parts that need consistent, repeatable geometry across a production run, and components with curved or irregular edge profiles that would be awkward to cut by hand. Because it''s driven directly from your file, the same profile comes out the same way on unit one and unit fifty.

Laser cutting, by comparison, tends to suit finer or more intricate detail — small internal features, decorative or branded elements, and prototype work where you want to see a design before committing to a full run.

In practice, a lot of parts use routing for the main profile and mounting geometry, with laser cutting reserved for fine detail work within that same part. Which one (or both) makes sense for a given component comes down to the geometry itself more than any general rule.

If you''re not sure which process your part needs, that''s a normal thing to leave to us — send the drawing and quantity, and we''ll fabricate it using whichever combination of cutting methods actually fits the geometry.', 'Henil Enterprise', true, '2026-02-12');
insert into blog_posts (slug, title, excerpt, content, author, published, published_at) values ('laser-cutting', 'Laser Cutting Acrylic and Polycarbonate: Where It Excels', 'Laser cutting isn''t a replacement for CNC routing — it''s the better tool for a specific kind of geometry.', 'Laser cutting uses a guided laser rather than a mechanical bit to cut through sheet material, and the difference in method is exactly why it suits different work than CNC routing does.

Because there''s no physical cutting tool making contact with the material, laser cutting handles intricate or detailed profiles — fine internal features, decorative or branded elements, small precision components — more cleanly than mechanical cutting typically can. It''s also a strong fit for prototype work, where you want an accurate, clean-edged part quickly before committing to a full production run.

Both acrylic and polycarbonate can be laser cut, though the two materials behave a little differently under the process, which is part of why we treat them as related but distinct capabilities rather than one interchangeable process.

Laser cutting isn''t the default choice for every job — for panels that need multiple mounting holes and a repeatable production profile across a large batch, CNC routing is often the more practical fit. The two processes complement each other more than they compete, and a single component sometimes uses both.

If your part has fine detail work, a prototype timeline, or a design you want to see before scaling up, mention that when you request a quote — it''s exactly the kind of context that helps us choose the right process from the start.', 'Henil Enterprise', true, '2026-02-19');
insert into blog_posts (slug, title, excerpt, content, author, published, published_at) values ('acrylic-bending', 'Acrylic Bending: Getting a Folded Edge Without a Seam', 'Heat-forming acrylic to an angle avoids a bonded corner entirely — useful more often than it gets considered.', 'Acrylic bending heat-forms a sheet to a specified angle, producing a folded or curved component from a single piece rather than two pieces joined at a bonded corner.

The appeal is straightforward: a bent corner has no seam, which means no bond line to fail under stress and no visible joint to finish. For components combining a flat section with a folded edge — a display stand, an enclosure corner, a point-of-sale fixture — bending often produces a stronger and cleaner result than bonding two flat pieces together would.

It''s not always the right choice, though. Bending works within the geometry a single sheet can be formed into; a component with multiple angles, a genuinely three-dimensional shape, or panels that need to be different thicknesses is usually better served by cutting and bonding separate pieces instead. The decision generally comes down to whether the part''s shape can reasonably come from one folded sheet or needs to be assembled from several.

Consistency across a production run matters here too — a formed batch should hold the same bend angle from the first unit to the last, which is part of why bending is treated as a controlled fabrication process rather than something done freehand per piece.

If your component has a folded edge in the design, it''s worth asking whether bending is the better fit before defaulting to a bonded corner — send the drawing and we''ll tell you which approach suits the geometry.', 'Henil Enterprise', true, '2026-02-26');
insert into blog_posts (slug, title, excerpt, content, author, published, published_at) values ('acrylic-bonding', 'Acrylic Bonding: How Multi-Part Assemblies Get Built', 'Bonding is how a component too large or too complex for a single sheet becomes one finished assembly.', 'Bonding joins separate acrylic (or polycarbonate) pieces into a single finished assembly, using solvent or adhesive bonding depending on the joint and the application.

It''s the process that makes larger or more complex components possible in the first place. A multi-panel enclosure, a tank, a cabinet — anything too large or too intricately shaped to cut from one piece of sheet — gets built by cutting the individual panels to size and bonding them together into the finished part.

Bonding also comes into play alongside other processes rather than instead of them. A component might be CNC routed for its panel profiles, then bonded at the seams, with a bent corner where a fold makes more sense than a joint. Which combination applies depends on the part''s actual geometry, not a fixed sequence.

The quality of a bonded joint matters as much as the cut quality of the panels themselves — a clean, properly bonded seam holds up under the same conditions the rest of the assembly needs to handle, which is why bonding gets treated as a precision process rather than an afterthought once the pieces are cut.

If your component is larger than a single sheet or combines multiple panels, bonding is likely part of how it gets built — send your drawing and we''ll work out the panel breakdown and joint approach as part of the quote.', 'Henil Enterprise', true, '2026-03-05');
insert into blog_posts (slug, title, excerpt, content, author, published, published_at) values ('industrial-applications', 'Where Acrylic and Polycarbonate Fabrication Actually Gets Used', 'A tour through the industrial applications where fabricated acrylic and polycarbonate components show up — and why.', 'Fabricated acrylic and polycarbonate components show up across a wider range of industrial applications than people usually expect, and the common thread across almost all of them is the same: something needs to be seen through while also being protected, contained, or guarded.

Machine guards and safety shields are the most visible category — anywhere a hazard needs a barrier that doesn''t block visibility, a fabricated guard is usually the answer. Inspection windows and sight glasses serve a related purpose on a smaller scale: letting someone monitor an enclosed process without opening the housing.

Containment shows up too — tanks and enclosures built for process fluids or sensitive equipment, where clarity for monitoring matters alongside the containment itself. On the commercial side, boxes, cabinets, and display fixtures use the same core fabrication processes for a very different purpose: presentation rather than protection.

Across industries — pharmaceutical, food processing, automotive, general manufacturing — the specific application shifts, but the underlying requirement stays consistent: a component built to fit a specific piece of equipment or a specific process, not pulled from a generic parts bin.

If you''re trying to figure out whether your application is a good fit for fabricated acrylic or polycarbonate, our Industrial Applications section and Industries page cover the categories in more depth — or you can just describe what you''re trying to protect, contain, or display and we''ll tell you what fits.', 'Henil Enterprise', true, '2026-03-12');

