// Central SEO copy for static routes. Kept separate from the components
// that render each page for the same reason NAV_LINKS and CAPABILITIES
// live in site.config.js — one place to edit, no risk of a title tag
// drifting out of sync with what a page actually says.
//
// Approach: each page targets a distinct slice of real search intent
// rather than every page repeating the same "Ahmedabad" keyword list —
// that's what the brief asked for ("do not keyword stuff") and it's
// also just how search intent actually splits: someone searching
// "acrylic machine guard Ahmedabad" wants the machine-guards page, not
// the homepage restating the same phrase back at them.
//
// Titles stay under ~60 characters where possible (Google truncates
// beyond that); descriptions sit in the ~150-160 character range.

export const SEO = {
  home: {
    title: "Acrylic & Polycarbonate Manufacturer in Ahmedabad | Henil Enterprise",
    description:
      "Henil Enterprise is a B2B acrylic and polycarbonate manufacturer and fabricator based in Ahmedabad, Gujarat, building custom components to your drawing for businesses across India.",
    path: "/",
  },
  about: {
    title: "About Us | Acrylic & Polycarbonate Fabricator in Ahmedabad",
    description:
      "Henil Enterprise is an Ahmedabad-based acrylic and polycarbonate fabricator working business-to-business — components built to your drawing, dimensions, sample, or specification.",
    path: "/about",
  },
 products: {
  title: "Acrylic & Polycarbonate Products Manufacturer Ahmedabad | Henil Enterprise",
  description:
    "Explore custom acrylic and polycarbonate products from Henil Enterprise, Ahmedabad — machine guards, covers, boxes, components and fabricated parts made to your drawing.",
  path: "/products",
},
  capabilities: {
    title: "CNC Routing, Laser Cutting, Bending & Bonding | Ahmedabad Fabrication",
    description:
      "Acrylic and polycarbonate fabrication capabilities in Ahmedabad — CNC routing, laser cutting, precision cutting, heat bending, bonding, and full custom fabrication from your drawing.",
    path: "/capabilities",
  },
  industries: {
    title: "Industries We Serve | Industrial Acrylic Fabrication in Ahmedabad",
    description:
      "Industrial acrylic and polycarbonate fabrication for pharmaceutical, food processing, electronics, automotive and other industries — from our Ahmedabad manufacturing base.",
    path: "/industries",
  },
  gallery: {
    title: "Our Work | Acrylic & Polycarbonate Fabrication Gallery, Ahmedabad",
    description:
      "See the acrylic and polycarbonate fabrication process at our Ahmedabad facility — from raw sheet through CNC routing, laser cutting, bending and finished dispatch.",
    path: "/gallery",
  },
  blog: {
    title: "Blog | Acrylic & Polycarbonate Fabrication Insights — Henil Enterprise",
    description:
      "Notes on acrylic and polycarbonate fabrication — materials, processes, and applications — from Henil Enterprise, an Ahmedabad-based manufacturer and fabricator.",
    path: "/blog",
  },
  contact: {
    title: "Contact Us | Acrylic & Polycarbonate Fabricator in Ahmedabad",
    description:
      "Reach Henil Enterprise in Ahmedabad, Gujarat by phone, email or WhatsApp, or send your drawing directly for a fabrication quote. Serving customers across India.",
    path: "/contact",
  },
  faq: {
    title: "Frequently Asked Questions | Henil Enterprise, Ahmedabad",
    description:
      "Answers to common questions about acrylic and polycarbonate fabrication, quantity orders, custom drawings, delivery and quoting at Henil Enterprise, Ahmedabad.",
    path: "/faq",
  },
  quote: {
    title: "Get a Quote | Acrylic & Polycarbonate Fabrication, Ahmedabad",
    description:
      "Request a fabrication quote from Henil Enterprise — share your drawing, dimensions, sample or specification and our Ahmedabad team will respond with a quote.",
    path: "/quote",
  },
  brochure: {
    title: "Company Brochure | Henil Enterprise, Ahmedabad",
    description:
      "Download the Henil Enterprise brochure — capabilities, product range, and fabrication process from our Ahmedabad acrylic and polycarbonate manufacturing facility.",
    path: "/brochure",
  },
};

// Product pages are dynamic, so their SEO fields are generated by
// category. Each category targets a distinct search intent without
// repeating the same keywords across every product page.

export function buildProductSeo(product, category) {
  const seoByCategory = {
    "industrial-acrylic-components": {
      title: "Industrial Acrylic Components Manufacturer Ahmedabad",
      description:
        "Custom industrial acrylic components manufactured in Ahmedabad by Henil Enterprise for machinery, equipment and engineering applications.",
    },

    "polycarbonate-components": {
      title: "Polycarbonate Components Manufacturer Ahmedabad",
      description:
        "Custom polycarbonate components manufactured in Ahmedabad by Henil Enterprise for industrial, protective and engineering applications.",
    },

    "machine-guards": {
      title:
        product.materials?.length === 1
          ? `${product.materials[0]} Machine Guard Manufacturer Ahmedabad`
          : "Acrylic & Polycarbonate Machine Guards Ahmedabad",
      description:
        "Custom machine guards fabricated from acrylic and polycarbonate in Ahmedabad for CNC machines, conveyors and industrial equipment.",
    },

    "protective-covers": {
      title: "Acrylic & Polycarbonate Protective Covers Ahmedabad",
      description:
        "Custom acrylic and polycarbonate protective covers manufactured in Ahmedabad for control panels, equipment and industrial applications.",
    },

    "acrylic-tanks": {
      title: "Custom Acrylic Tank Manufacturer Ahmedabad",
      description:
        "Custom acrylic tanks fabricated in Ahmedabad by Henil Enterprise to your capacity, configuration and drawing requirements.",
    },

    "acrylic-boxes": {
      title: "Custom Acrylic Boxes Manufacturer Ahmedabad",
      description:
        "Custom clear acrylic boxes manufactured in Ahmedabad for storage, display and industrial applications according to your requirements.",
    },

    "acrylic-cabinets": {
      title: "Acrylic Display Cabinets Manufacturer Ahmedabad",
      description:
        "Custom acrylic display cabinets manufactured in Ahmedabad for retail, showroom and light storage applications.",
    },

    "inspection-windows": {
      title: "Acrylic & Polycarbonate Inspection Windows Ahmedabad",
      description:
        "Custom acrylic and polycarbonate inspection windows fabricated in Ahmedabad for machine housings and process monitoring applications.",
    },

    "sight-glasses": {
      title: "Acrylic Sight Glass Manufacturer Ahmedabad",
      description:
        "Custom acrylic sight glass components fabricated in Ahmedabad for visual monitoring of tanks, equipment and enclosed processes.",
    },

    "transparent-enclosures": {
      title: "Acrylic & Polycarbonate Enclosures Ahmedabad",
      description:
        "Custom transparent acrylic and polycarbonate equipment enclosures manufactured in Ahmedabad for visibility and equipment protection.",
    },

    "custom-fabricated-components": {
      title: "Custom Acrylic & Polycarbonate Components Ahmedabad",
      description:
        "Custom acrylic and polycarbonate components fabricated in Ahmedabad from your drawing, sample or specification for industrial applications.",
    },

    "display-commercial-products": {
      title: "Acrylic Display Products Manufacturer Ahmedabad",
      description:
        "Custom acrylic display and point-of-sale products manufactured in Ahmedabad for retail, commercial spaces and showrooms.",
    },
  };

  const categorySeo = seoByCategory[product.categoryId];

  if (categorySeo) {
    return {
      title: categorySeo.title,
      description: categorySeo.description,
      path: `/products/${product.id}`,
    };
  }

  // Safe fallback for any future category added to the catalogue.
  return {
    title: `${product.name} | ${category?.label || "Custom Fabrication"} — Ahmedabad`,
    description:
      `${product.shortDescription} Fabricated in Ahmedabad, Gujarat by Henil Enterprise for businesses across India — request a quote for your quantity.`.slice(
        0,
        160
      ),
    path: `/products/${product.id}`,
  };
}

export function buildBlogPostSeo(post) {
  return {
    title: `${post.title} | Henil Enterprise Blog`,
    description: post.excerpt,
    path: `/blog/${post.slug}`,
  };
}
