-- ============================================================
-- inquiries
-- Backs the /quote RFQ wizard (frontend/src/pages/Quote.jsx). Field
-- list, types, and the status lifecycle match exactly what was
-- specified — nothing added or removed.
--
-- KNOWN GAP (documented, not silently worked around): the live wizard
-- currently stores a free-text product name (the customer can type
-- anything, including a product not in the catalogue) alongside an
-- optional productId from a prefilled product-page link. The field list
-- given here is `product_id` only — implemented faithfully below as a
-- nullable FK — but wiring the real form to this table will need a
-- decision: either reject free-text-only submissions, or add a
-- `product_name_text` column in a follow-up migration. Not resolved
-- here since it wasn't part of the requested field list.
--
-- length/width/height/thickness are text, not numeric — the wizard
-- collects free-text values like "600mm" or "5mm", not parsed numbers
-- with a separate unit column. Storing invented numeric precision that
-- was never actually captured would be worse than storing what was
-- really submitted.
-- ============================================================

create table inquiries (
  id                      uuid primary key default gen_random_uuid(),
  reference_number        text not null unique,

  company_name            text not null,
  contact_person          text not null,
  email                   text not null,
  phone                   text not null,
  gst_number              text,
  city                    text,
  country                 text,

  product_id              uuid references products (id) on delete set null,
  quantity                integer not null,
  material                text not null,
  thickness               text,

  length                  text,
  width                   text,
  height                  text,
  custom_dimensions       text,
  drawing_reference       text,

  required_delivery_date  date,
  delivery_location       text,

  message                 text,

  status                  inquiry_status not null default 'NEW',

  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),

  constraint inquiries_reference_number_format
    check (reference_number ~ '^HE-RFQ-[0-9]{5,}$'),
  constraint inquiries_email_format
    check (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  constraint inquiries_quantity_positive
    check (quantity > 0),
  -- Matches MATERIAL_OPTIONS in frontend/src/data/quoteForm.data.js
  -- exactly. Adding a material there means adding it here too.
  constraint inquiries_material_known
    check (material in ('acrylic', 'polycarbonate', 'unsure'))
);

comment on table inquiries is
  'RFQ submissions from /quote. reference_number is generated by the backend counter service (backend/src/services/inquiryCounter.service.js), not by the database — kept as an application-supplied unique value here.';

create index idx_inquiries_status on inquiries (status);
create index idx_inquiries_email on inquiries (email);
create index idx_inquiries_created_at on inquiries (created_at desc);
create index idx_inquiries_product_id on inquiries (product_id);

create trigger trg_inquiries_updated_at
  before update on inquiries
  for each row execute function set_updated_at();
